export const NOTIFICATION_TIME_ZONE = "Asia/Shanghai";
export const NOTIFICATION_BATCH_SIZE = 500;
export const NOTIFICATION_MAX_TITLE_LENGTH = 100;
export const NOTIFICATION_MAX_CONTENT_LENGTH = 2_000;
export const ASSIGNMENT_DUE_REMINDER_HOURS = 24;
export const ASSIGNMENT_REMINDER_ASSIGNMENT_LIMIT = 100;
