ALTER TYPE "AuditAction" ADD VALUE 'SUBMISSION_GRADING_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE 'ASSIGNMENT_RESULTS_PUBLISHED';

ALTER TYPE "AuditTargetType" ADD VALUE 'SUBMISSION';
ALTER TYPE "AuditTargetType" ADD VALUE 'ASSIGNMENT';
