ALTER TYPE "AuditAction" ADD VALUE 'QUESTION_MADE_PUBLIC';
ALTER TYPE "AuditAction" ADD VALUE 'QUESTION_MADE_PRIVATE';
ALTER TYPE "AuditAction" ADD VALUE 'QUESTION_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE 'CLASSROOM_CLOSED_BY_ADMIN';

ALTER TYPE "AuditTargetType" ADD VALUE 'QUESTION';
ALTER TYPE "AuditTargetType" ADD VALUE 'CLASSROOM';
